server:
  port: 8201
  
spring:
  application:
    name: hello-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
      
logging:
  config: classpath:logback-spring.xml
  path: C:\Users\line\Desktop\myCloud\logs
  
feign:
  hystrix:
    enabled: true